language: android
jdk: oraclejdk8
sudo: required

notifications:
  email: false

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
    - android-22
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

after_script:
  - docker exec -it rpi cat /var/log/apache2/access.log

services:
  - docker

before_install:
  - docker run -d -p 4000:80 -p 5000:3306  -t rpi ftamagny/embedded
  - yes | sdkmanager --update
  - yes | sdkmanager "platforms;android-27"
  - wget 127.0.0.1:4000/api.php 

script:
  - "./gradlew clean build connectedAndroidTest --stacktrace"   